// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_token from "./routes/api/token.ts";
import * as $create_post from "./routes/create/post.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $lib from "./routes/lib.ts";
import * as $login from "./routes/login.tsx";
import * as $posts_id_ from "./routes/posts/[id].tsx";
import * as $search from "./routes/search.tsx";
import * as $signout from "./routes/signout.tsx";
import * as $user_posts_name_ from "./routes/user/posts/[name].tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $CreatePost from "./islands/CreatePost.tsx";
import * as $Redirect from "./islands/Redirect.tsx";
import * as $Reply from "./islands/Reply.tsx";
import * as $Search from "./islands/Search.tsx";
import * as $Server from "./islands/Server.tsx";
import * as $Signin from "./islands/Signin.tsx";
import * as $SupaClient from "./islands/SupaClient.tsx";
import * as $User from "./islands/User.tsx";
import * as $Yolo from "./islands/Yolo.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/token.ts": $api_token,
    "./routes/create/post.tsx": $create_post,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/lib.ts": $lib,
    "./routes/login.tsx": $login,
    "./routes/posts/[id].tsx": $posts_id_,
    "./routes/search.tsx": $search,
    "./routes/signout.tsx": $signout,
    "./routes/user/posts/[name].tsx": $user_posts_name_,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/CreatePost.tsx": $CreatePost,
    "./islands/Redirect.tsx": $Redirect,
    "./islands/Reply.tsx": $Reply,
    "./islands/Search.tsx": $Search,
    "./islands/Server.tsx": $Server,
    "./islands/Signin.tsx": $Signin,
    "./islands/SupaClient.tsx": $SupaClient,
    "./islands/User.tsx": $User,
    "./islands/Yolo.tsx": $Yolo,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
