create table "public"."comments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "post_id" bigint,
    "user_id" bigint,
    "body" text,
    "parent_comment_id" bigint
);


alter table "public"."comments" enable row level security;

create table "public"."communities" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "creator_id" bigint
);


alter table "public"."communities" enable row level security;

create table "public"."moderators" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint,
    "community_id" bigint
);


alter table "public"."moderators" enable row level security;

create table "public"."posts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text,
    "body" text,
    "user_id" bigint,
    "category" text,
    "community_id" bigint default '1'::bigint,
    "pinned" boolean
);


alter table "public"."posts" enable row level security;

create table "public"."users" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "username" text,
    "user_id" uuid default gen_random_uuid()
);


alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX comments_pkey ON public.comments USING btree (id);

CREATE UNIQUE INDEX communities_pkey ON public.communities USING btree (id);

CREATE UNIQUE INDEX moderators_pkey ON public.moderators USING btree (id);

CREATE UNIQUE INDEX posts_pkey ON public.posts USING btree (id);

CREATE UNIQUE INDEX usernames_pkey ON public.users USING btree (id);

CREATE UNIQUE INDEX usernames_user_id_key ON public.users USING btree (user_id);

CREATE UNIQUE INDEX usernames_username_key ON public.users USING btree (username);

alter table "public"."comments" add constraint "comments_pkey" PRIMARY KEY using index "comments_pkey";

alter table "public"."communities" add constraint "communities_pkey" PRIMARY KEY using index "communities_pkey";

alter table "public"."moderators" add constraint "moderators_pkey" PRIMARY KEY using index "moderators_pkey";

alter table "public"."posts" add constraint "posts_pkey" PRIMARY KEY using index "posts_pkey";

alter table "public"."users" add constraint "usernames_pkey" PRIMARY KEY using index "usernames_pkey";

alter table "public"."comments" add constraint "comments_post_id_fkey" FOREIGN KEY (post_id) REFERENCES posts(id) not valid;

alter table "public"."comments" validate constraint "comments_post_id_fkey";

alter table "public"."comments" add constraint "comments_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT not valid;

alter table "public"."comments" validate constraint "comments_user_id_fkey";

alter table "public"."communities" add constraint "communities_creator_id_fkey" FOREIGN KEY (creator_id) REFERENCES users(id) not valid;

alter table "public"."communities" validate constraint "communities_creator_id_fkey";

alter table "public"."moderators" add constraint "moderators_community_id_fkey" FOREIGN KEY (community_id) REFERENCES communities(id) not valid;

alter table "public"."moderators" validate constraint "moderators_community_id_fkey";

alter table "public"."moderators" add constraint "moderators_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."moderators" validate constraint "moderators_user_id_fkey";

alter table "public"."posts" add constraint "posts_community_id_fkey" FOREIGN KEY (community_id) REFERENCES communities(id) not valid;

alter table "public"."posts" validate constraint "posts_community_id_fkey";

alter table "public"."posts" add constraint "posts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."posts" validate constraint "posts_user_id_fkey";

alter table "public"."users" add constraint "usernames_user_id_key" UNIQUE using index "usernames_user_id_key";

alter table "public"."users" add constraint "usernames_username_key" UNIQUE using index "usernames_username_key";

grant delete on table "public"."comments" to "anon";

grant insert on table "public"."comments" to "anon";

grant references on table "public"."comments" to "anon";

grant select on table "public"."comments" to "anon";

grant trigger on table "public"."comments" to "anon";

grant truncate on table "public"."comments" to "anon";

grant update on table "public"."comments" to "anon";

grant delete on table "public"."comments" to "authenticated";

grant insert on table "public"."comments" to "authenticated";

grant references on table "public"."comments" to "authenticated";

grant select on table "public"."comments" to "authenticated";

grant trigger on table "public"."comments" to "authenticated";

grant truncate on table "public"."comments" to "authenticated";

grant update on table "public"."comments" to "authenticated";

grant delete on table "public"."comments" to "service_role";

grant insert on table "public"."comments" to "service_role";

grant references on table "public"."comments" to "service_role";

grant select on table "public"."comments" to "service_role";

grant trigger on table "public"."comments" to "service_role";

grant truncate on table "public"."comments" to "service_role";

grant update on table "public"."comments" to "service_role";

grant delete on table "public"."communities" to "anon";

grant insert on table "public"."communities" to "anon";

grant references on table "public"."communities" to "anon";

grant select on table "public"."communities" to "anon";

grant trigger on table "public"."communities" to "anon";

grant truncate on table "public"."communities" to "anon";

grant update on table "public"."communities" to "anon";

grant delete on table "public"."communities" to "authenticated";

grant insert on table "public"."communities" to "authenticated";

grant references on table "public"."communities" to "authenticated";

grant select on table "public"."communities" to "authenticated";

grant trigger on table "public"."communities" to "authenticated";

grant truncate on table "public"."communities" to "authenticated";

grant update on table "public"."communities" to "authenticated";

grant delete on table "public"."communities" to "service_role";

grant insert on table "public"."communities" to "service_role";

grant references on table "public"."communities" to "service_role";

grant select on table "public"."communities" to "service_role";

grant trigger on table "public"."communities" to "service_role";

grant truncate on table "public"."communities" to "service_role";

grant update on table "public"."communities" to "service_role";

grant delete on table "public"."moderators" to "anon";

grant insert on table "public"."moderators" to "anon";

grant references on table "public"."moderators" to "anon";

grant select on table "public"."moderators" to "anon";

grant trigger on table "public"."moderators" to "anon";

grant truncate on table "public"."moderators" to "anon";

grant update on table "public"."moderators" to "anon";

grant delete on table "public"."moderators" to "authenticated";

grant insert on table "public"."moderators" to "authenticated";

grant references on table "public"."moderators" to "authenticated";

grant select on table "public"."moderators" to "authenticated";

grant trigger on table "public"."moderators" to "authenticated";

grant truncate on table "public"."moderators" to "authenticated";

grant update on table "public"."moderators" to "authenticated";

grant delete on table "public"."moderators" to "service_role";

grant insert on table "public"."moderators" to "service_role";

grant references on table "public"."moderators" to "service_role";

grant select on table "public"."moderators" to "service_role";

grant trigger on table "public"."moderators" to "service_role";

grant truncate on table "public"."moderators" to "service_role";

grant update on table "public"."moderators" to "service_role";

grant delete on table "public"."posts" to "anon";

grant insert on table "public"."posts" to "anon";

grant references on table "public"."posts" to "anon";

grant select on table "public"."posts" to "anon";

grant trigger on table "public"."posts" to "anon";

grant truncate on table "public"."posts" to "anon";

grant update on table "public"."posts" to "anon";

grant delete on table "public"."posts" to "authenticated";

grant insert on table "public"."posts" to "authenticated";

grant references on table "public"."posts" to "authenticated";

grant select on table "public"."posts" to "authenticated";

grant trigger on table "public"."posts" to "authenticated";

grant truncate on table "public"."posts" to "authenticated";

grant update on table "public"."posts" to "authenticated";

grant delete on table "public"."posts" to "service_role";

grant insert on table "public"."posts" to "service_role";

grant references on table "public"."posts" to "service_role";

grant select on table "public"."posts" to "service_role";

grant trigger on table "public"."posts" to "service_role";

grant truncate on table "public"."posts" to "service_role";

grant update on table "public"."posts" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";

create policy "Enable insert for users based on user_id"
on "public"."comments"
as permissive
for insert
to public
with check ((( SELECT auth.uid() AS uid) = ( SELECT users.user_id
   FROM users
  WHERE (users.id = comments.user_id))));


create policy "Enable read access for all users"
on "public"."comments"
as permissive
for select
to public
using (true);


create policy "update comment based on id"
on "public"."comments"
as permissive
for update
to public
using ((( SELECT auth.uid() AS uid) = ( SELECT users.user_id
   FROM users
  WHERE (users.id = comments.user_id))));


create policy "Enable read access for all users"
on "public"."communities"
as permissive
for select
to public
using (true);


create policy "insert"
on "public"."communities"
as permissive
for insert
to public
with check ((( SELECT auth.uid() AS uid) = ( SELECT users.user_id
   FROM users
  WHERE (users.id = communities.creator_id))));


create policy "insert"
on "public"."moderators"
as permissive
for insert
to public
with check ((( SELECT auth.uid() AS uid) = ( SELECT users.user_id
   FROM users
  WHERE (users.id = moderators.user_id))));


create policy "Enable insert for users based on user_id"
on "public"."posts"
as permissive
for insert
to public
with check ((( SELECT auth.uid() AS uid) = ( SELECT users.user_id
   FROM users
  WHERE (users.id = posts.user_id))));


create policy "Enable read access for all users"
on "public"."posts"
as permissive
for select
to public
using (true);


create policy "update posts based on user id"
on "public"."posts"
as permissive
for update
to public
using ((( SELECT auth.uid() AS uid) = ( SELECT users.user_id
   FROM users
  WHERE (users.id = posts.user_id))));


create policy "Enable insert for users based on user_id"
on "public"."users"
as permissive
for insert
to public
with check ((( SELECT auth.uid() AS uid) = user_id));


create policy "Enable read access for all users"
on "public"."users"
as permissive
for select
to public
using (true);



